version: '3'
services:
  cloudflare-dns:
    build: .
    image: qmcgaw/cloudflare-dns-server
    container_name: dns
    environment:
      - VERBOSITY=
      - VERBOSITY_DETAILS=
      - BLOCK_MALICIOUS=
      - LISTENINGPORT=
    ports:
      - 53:53/udp
    network_mode: bridge
