version: '3'
services:
    cloudflare-dns:
        image: qmcgaw/cloudflare-dns-server
        container_name: cloudflare-dns
        ports:
            - 53:53/tcp
        network_mode: bridge
        restart: always