version: '3'
services:
  cloudflare-dns:
    image: qmcgaw/cloudflare-dns-server
    container_name: cloudflare-dns-tls
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=on
    ports:
      - 53:53/udp
    dns:
      - 127.0.0.1
      # The container DNS is changed to localhost for the healthcheck
    network_mode: bridge
    restart: always
